### ISSUE TITLE
make it possible to move elements to an empty list

### ISSUE THREAD

**Issue by lusy** [lusy/cats#6]
here are some issues of the "sortable.js" library which could be relevant/related:
- https://github.com/RubaXa/Sortable/issues/591
- https://github.com/RubaXa/Sortable/issues/18
- https://github.com/RubaXa/Sortable/issues/472

**Comment by shageevan** [comment]
1. Add `min-height` to your `ul` element.
2. Add a class to your `li`. Use the same class in `draggable` option

**Comment by lusy** [comment]
Hey @shageevan,  thank you very much for your suggestion! It solved the issue :)
Do you have by any chance some idea about #11 too? I've got the feeling, the problem may be related to this one.

**Comment by shageevan** [comment]
Hi @lusy, glad to hear that. I'll check #11 and comment there.

**Comment by SteveShe** [comment]
Being a CSS/Javascript noob, I struggled to make this work and understand why it was broken. Further investigation made it clear, so I thought I would share it here, so other noobs won't take as long to get it fixed as I did. 

The problem is that without a 'min-height' property on the `<ul>` element, the `<ul>` height is effectively 0 (zero) and can't be targeted by the incoming `<li>`. You can see this by using something like the chrome debugger to inpect the `<ul>` element on the page when it is empty.

![image](https://cloud.githubusercontent.com/assets/15335295/18359479/c1988ea4-75bf-11e6-87cc-133415dc0161.png)

As was stated above, you need to add the 'min-height' property to the CSS that is being applied to the `<ul>`, like so:

`.list-group {
  margin-bottom: 20px;
  padding-left: 0;
  min-height: 200px;
}`

and make you tell Sortable what class it should expect to be dragged into the list. This class needs to match the CSS definition you used on the `<li>`, **NOT the `<ul>` element**:

``` javascript
var bugTags = new Sortable.create(byId('bug-tags'), {
        group: {
            name:'tags',
            pull:true,
            put:true
        },
        sort:true,
        animation:150,
        draggable: '.list-group-item',
```

when you reinspect the element you can see that it now has a height that makes it targetable with the `<li>` element you are dragging in:

![image](https://cloud.githubusercontent.com/assets/15335295/18359316/06f2c9b6-75bf-11e6-91c7-8b8308e78eef.png)
